//Since there is no real backend (and none needed), this is just a
//global var where a mongodb-like object is set up.

var beersDB = {
  queenbee: {
    name: "Queen Bee",
    urlName: "queenbee",
    shortDesc:
      "The Queen Bee is a delicious dry hopped IPA (7.7% ABV) with a smooth citrus hoppy flavor. It has a yellow/orange color with a firm hoppy foam. The Queen Bee is an English style IPA with an American hop. We used a single hop, Cascade. The hop is used during the boil for bitterness, and during dry-hopping for aroma. It gives a nice, refreshing, fruity IPA with taste of grapefruit. ",
    longDesc: "",
    artist: "Kiana Girigorie",
    artistUrl: "http://instagram.com/kiana.girigorie",
    backgroundColor: "#edefed",
    labelImageUrl: "./imgs/wide-label-queenbee.jpg",
    untappdId: "1232681",
    ABV: 7.7,
    beerType: "IPA",
    hexImageUrl: "imgs/hexes/queen-bee.png",
    order: 2,
  },
  worker: {
    name: "Worker",
    urlName: "worker",
    shortDesc:
      "Our tasty Imperial Saison, the Worker (9.4% ABV), is prickly sweet with some spiciness. The Worker has aroma notes of over-ripened peaches, dates, and stone fruit. The rye is very apparent and gives the beer a spicy floral taste.",
    longDesc: "",
    artist: "Kiana Girigorie",
    artistUrl: "http://instagram.com/kiana.girigorie",
    backgroundColor: "#c0bbdc",
    labelImageUrl: "./imgs/wide-label-worker.jpg",
    untappdId: "1372512",
    ABV: 9.4,
    beerType: "Saison / Farmhouse Ale",
    hexImageUrl: "imgs/hexes/worker.png",
    order: 3,
  },
  honeyblonde: {
    name: "Honey",
    urlName: "honeyblonde",
    shortDesc:
      "Nice, fruity blonde beer, the Honey has notes of lemon, orange and star anise. The Honey is strong and has a full body. The taste is light sweet and fresh bitter.",
    longDesc: "",
    artist: "Luna Bongers",
    artistUrl: "http://instagram.com/LunaBongers",
    backgroundColor: "#f5f0e7",
    labelImageUrl: "./imgs/wide-label-honey.jpg",
    untappdId: "1372507",
    ABV: 7.9,
    beerType: "Belgian Blonde",
    hexImageUrl: "imgs/hexes/honey.png",
    order: 1,
  },
  smoker: {
    name: "Smoker",
    new: false,
    urlName: "smoker",
    shortDesc:
      "Smoker (5.4% ABV) is a subtle Rauchbier. It has a very clean smokiness with pleasant sweetness and complex flavours that come from the malt.",
    longDesc: "",
    artist: "Bernadette Leijdekkers",
    artistUrl: "http://www.leijdekkers.nl/",
    backgroundColor: "#5fb5bf",
    labelImageUrl: "./imgs/wide-label-smoker.jpg",
    untappdId: "1549422",
    ABV: 5.4,
    beerType: "Rauchbier",
    hexImageUrl: "imgs/hexes/smoker.png",
    order: 4,
  },
  hive: {
    new: false,
    name: "Hive",
    urlName: "hive",
    shortDesc:
      "Hive (5,3% ABV) is a very fresh Hefeweizen. The Hive is made up of a lot of wheat which gives it a refreshing taste. It is cloudy and pale, with a foamy and frothy head. The taste is fruity and has some vanilla flavors. ",
    longDesc: "",
    artist: "Bernadette Leijdekkers",
    artistUrl: "http://www.leijdekkers.nl/",
    backgroundColor: "#c3dbe4",
    labelImageUrl: "./imgs/wide-label-hive.jpg",
    untappdId: "1572399",
    ABV: 5.3,
    beerType: "Hefeweizen",
    hexImageUrl: "imgs/hexes/hive.png",
    order: 5,
  },
  drone2: {
    name: "Drone²",
    urlName: "drone2",
    shortDesc:
      "Drone² (8.5% ABV) is the successor of the Drone which we stopped producing. We increased the ingredients to get more aromas of roasted malt, chocolate, caramel and coffee! And of course, the alcohol percentage increased with it. The Drone² s our only beer with an artwork representing a male; we couldn't put a female artwork on a male bee ;-)",
    longDesc: "",
    artist: "Kiana Girigorie",
    artistUrl: "http://instagram.com/kiana.girigorie",
    backgroundColor: "#59acda",
    labelImageUrl: "./imgs/wide-label-drone2.jpg",
    untappdId: "1549431",
    ABV: 8.5,
    beerType: "Imperial Porter",
    hexImageUrl: "imgs/hexes/drone2.png",
    order: 6,
  },
  nectar: {
    name: "Nectar",
    urlName: "nectar",
    shortDesc:
      "Nectar (10.7% Abv.), our Barleywine, has a nice balance of malt and bitterness. The hops (Columbus, Chinook, Centennial, Simcoe, Amarillo) and malt work very well together.",
    longDesc: "",
    artist: "Cristiaan Lieverse",
    artistUrl: "http://www.christiaanlieverse.com/",
    backgroundColor: "#bcc5dc",
    labelImageUrl: "./imgs/wide-label-nectar.jpg",
    untappdId: "1549433",
    ABV: 10.7,
    beerType: "Barleywine",
    hexImageUrl: "imgs/hexes/nectar.png",
    order: 7,
  },
  // test:{
  //     new:true,
  //     name:"New test",
  //     urlName:'test',
  //     shortDesc: "this is a made up beer",
  //     longDesc: "",
  //     artist: "",
  //     artistUrl:"http://thesistersbrewery.com/",
  //     backgroundColor: '#e7d3cc',
  //     labelImageUrl: './imgs/hexes/genericlabel.png',
  //     untappdId:'2008963',
  //     ABV: 0.0,
  //     beerType: 'Fake',
  //     hexImageUrl:'imgs/hexes/genericlabel.png',
  //     order: 9
  waggle: {
    new: false,
    name: "Waggle Dance",
    urlName: "waggle",
    shortDesc:
      "Waggle Dance is our new session IPA. Hoppy, spicy and full bodied with nice soft hoppy foam. Made with Nugget, Citra and Mosaic. Dry hopped with Citra and Mosaic",
    longDesc: "",
    artist: "Toto Stoffels",
    artistUrl: "https://www.instagram.com/totomatenplukker/",
    backgroundColor: "#68a29a",
    labelImageUrl: "./imgs/WaggleDance-label.jpg",
    untappdId: "2008963",
    ABV: 4.4,
    beerType: "Session IPA",
    hexImageUrl: "imgs/hexes/waggledance.png",
    order: 8,
  },
  // abelha:{
  //     name:"Abelha",
  //     urlName:'abelha',
  //     new:true,
  //     shortDesc: "--",
  //     longDesc: "",
  //     artist: "  ",
  //     artistUrl:"",
  //     backgroundColor: '',
  //     labelImageUrl: './imgs/Abelha.jpg',
  //     untappdId:'1635987',
  //     order: 9
  // },
  bzzz: {
    name: "Bzzz",
    urlName: "bzzz",
    new: false,
    shortDesc: "Full bodied Doppelbock with a smooth malty finish.",
    longDesc: "Full bodied Doppelbock with a smooth malty finish.",
    artist: "Ward van Elk",
    artistUrl: "https://www.instagram.com/wardvanelk/",
    backgroundColor: "#f5f0e7",
    labelImageUrl: "./imgs/bzzz.jpg",
    untappdId: "1750801",
    ABV: 8,
    beerType: "Doppelbock",
    hexImageUrl: "imgs/hexes/bzzz.png",
    order: 9,
  },
  apis: {
    name: "Apis",
    urlName: "apis",
    new: false,
    shortDesc:
      "Tripel brewed with grapefruit and honey from bees around the brewery. Soft and sweet fruity with a nice bitterness.",
    longDesc: "",
    artist: "Loes Faber",
    artistUrl: "https://www.loesfaber.com",
    backgroundColor: "#f1c020",
    labelImageUrl: "./imgs/wide-label-Apis.jpg",
    untappdId: "2373007",
    ABV: 8.5,
    beerType: "Tripel",
    hexImageUrl: "imgs/hexes/apis.png",
    order: 10,
  },
  black: {
    name: "Black",
    urlName: "black",
    new: false,
    shortDesc:
      "Vanilla Zuidam Old Genever (5y On Oak) Milk Stout. Soft smooth Vanilla Milk Stout, Infused with Zuidam Old Genever aged 5 year on American oak. Before infusion we put the Madagascar vanilla beans for 2 months in the Old Genever. The taste is soft smooth with vanilla, toffee, oak and chocolate. We used for the Black and Yellow the same Stout with Lactose",
    longDesc: "",
    artist: "Anne Aimée Winkelhuis ",
    artistUrl: "https://hetwinkelhuis.nl/",
    backgroundColor: "#f5f0e7",
    labelImageUrl: "./imgs/black.jpg",
    untappdId: "2395229",
    ABV: 10.5,
    beerType: "Vanilla Old Genever Milk Stout",
    hexImageUrl: "imgs/hexes/black_hex.png",
    order: 11,
  },
  yellow: {
    name: "Yellow",
    urlName: "yellow",
    new: false,
    shortDesc:
      "Vanilla Zuidam Old Genever (12y On Oak) Milk Stout. Soft smooth Vanilla Milk Stout, Infused with Zuidam Old Genever aged 12 year on American oak. This Old Genever is rare and difficult to get in liquor stores. Before infusion we put the Madagascar vanilla beans for 2 months in the Old Genever. The taste is much softer and smoother then the Black.  The taste is very smooth with vanilla, toffee, oak and chocolate. We used for the Black and Yellow the same Stout with Lactose.",
    longDesc: "",
    artist: "Anne Aimée Winkelhuis ",
    artistUrl: "https://hetwinkelhuis.nl/",
    backgroundColor: "#f5f0e7",
    labelImageUrl: "./imgs/yellow.jpg",
    untappdId: "2395233",
    ABV: 10.5,
    beerType: "Vanilla Old Genever Milk Stout",
    hexImageUrl: "imgs/hexes/yellow_hex.png",
    order: 12,
  },
	pchela: {
    name: "Pchela",
    urlName: "pchela",
    new: true,
    shortDesc:
      "A deep black and powerful Russian Imperial Stout with a creamy dark foam head. Strong roasted complex aroma and taste. Silky mouthfeel with notes of chocolate, coffee, burnt grain and dark fruits.",
    longDesc: "",
    artist: "Luna Bongers",
    artistUrl: "http://instagram.com/LunaBongers",
    backgroundColor: "#E1D7CB",
    labelImageUrl: "./imgs/wide-label-Pchela.jpg",
    untappdId: "3575483",
    ABV: 10.5,
    beerType: "Russian Imperial Stout",
    hexImageUrl: "imgs/hexes/Pchela.png",
    order: 13,
  },
};
